apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-ms
spec:
  destination:
    name: ''
    namespace: argo-test
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/environments/dev-env-native
    repoURL: 'git@github.com:ShintaroUMEDA/demo-microservice.git'
    targetRevision: helm_test
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
