apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-ms-eks
  region: ap-northeast-1
  version: "1.26"
  tags: 
    'Owner': 'umeda.shintaro.3xk' 

managedNodeGroups:
  - name: sample-node
    instanceType: t2.medium
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/argocd_key.pub
    privateNetworking: true
    iam:
      attachPolicyARNs: 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    preBootstrapCommands:
      - |
        #!/bin/bash
        sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        sudo systemctl enable amazon-ssm-agent
        sudo systemctl start amazon-ssm-agent