name: env check

on:
  workflow_dispatch:

jobs:

  build:

    runs-on:  self-hosted
    strategy:
      matrix:
        native-services: [product-composite,product,recommendation,review]

    steps:
    - name: list items
      run: |
        echo "${{ matrix.native-services }} and ${{ matrix.native-services }}"
        echo ${{ matrix.native-services }}
