    
name: GraalVM build
on:
  workflow_dispatch:

jobs:
  build-my-app:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'adopt'
      - name: install dependencies
        uses: umeda-shintaro/setup-graalvm@main
        with:
          version: '22.3.2'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.ACTION_TOKEN }}
      - name: Build step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          ./gradlew :microservices:product-service:bootBuildImage --no-daemon
          ./gradlew :microservices:product-composite-service:bootBuildImage --no-daemon
          ./gradlew :microservices:recommendation-service:bootBuildImage --no-daemon
          ./gradlew :microservices:review-service:bootBuildImage --no-daemon

