# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
      
name: GraalVM Enterprise Edition build
on:
  workflow_dispatch:

jobs:
  build-my-app:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '21.1.0'
#           gds-token: ${{ secrets.GDS_TOKEN }}
          java-version: '11'
          components: 'native-image'
#           github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Example step
        run: |
          java --version
          native-image --version
