name: Helm2ECR

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [ self-hosted ]
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: assume role
      uses: umeda-shintaro/aws-cli@master
      with:
        args: sts assume-role --role-arn arn:aws:iam::550013351950:role/umeda-githubci-role --role-session-name AWSCLI-Session
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
#     - name: Configure AWS credentials
#       run: |
#         aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws configure set default.region ${{ secrets.AWS_REGION }}
#         aws sts assume-role --role-arn ${{ secrets.AWS_ROLE_ARN }} --role-session-name AWSCLI-Session
#     - run: echo "NODE_OPTIONS=--trace-warnings" >> "$GITHUB_ENV"
#     - uses: umeda-shintaro/configure-aws-credentials@master
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: umeda-shintaro/amazon-ecr-login@master

    - name: Package and push helm chart to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: kubernetes/helm/environments/dev-env-native
      run: |
        helm package $REPOSITORY
        helm push dev-env-native-1.0.0.tgz oci://$REGISTRY
        
        
